


#[theme]
#base = "Light"
#primaryColor="#2BB5E9"
#backgroundColor="#E87900"
#secondaryBackgroundColor="#2BB5E9"
#textColor="#31333F"
#font="sans serif"

[theme]

primaryColor="#E87900"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
