


#[theme]
#base = "Light"
#primaryColor="#2BB5E9"
#backgroundColor="#E87900"
#secondaryBackgroundColor="#2BB5E9"
#textColor="#31333F"
#font="sans serif"

[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#2BB5E9'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
